CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	company TEXT NOT NULL,
	email TEXT NOT NULL,
	phone TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skill_ratings(
	user_id INTEGER,
	skill TEXT NOT NULL,
	rating INTEGER NOT NULL,
	PRIMARY KEY(user_id, skill),
	FOREIGN KEY(user_id) REFERENCES users(id)
);
