CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	company TEXT NOT NULL,
	email TEXT NOT NULL,
	phone TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skills(
	id INTEGER,
	skill TEXT NOT NULL,
	rating INTEGER NOT NULL,
	PRIMARY KEY(id, skill),
	FOREIGN KEY(id) REFERENCES users(id)
);
